### ISSUE TITLE
[style] 홈 화면 수정

### ISSUE THREAD

**Issue by kacey0416** [weekFlex/Cartier#26]
## Task 내용
- [ ] 테이블 셀 그림자 재조정
- [ ] 슬라이드 삭제 색 조정
- [x] 추가된 할 일 없을때 화면

## 해당 task 관련 스크린샷
<img width="300" alt="스크린샷 2021-06-15 오후 10 02 14" src="https://user-images.githubusercontent.com/37579683/122057216-592a7a80-ce25-11eb-8f81-2729d1470d5b.png">

## related issue
#8 

## things to consider, personal feedback
놓친 부분들 있어서 올려둡니다ㅠㅠ!
