### ISSUE TITLE
[style] 할 일 리스트 layout

### ISSUE THREAD

**Issue by xwoud** [weekFlex/Cartier#3]
## Task 내용
- [x] 할 일 검색 - Search Bar로 구현하기
- [x] 각 카테고리 선택 - CollectionView로 구현하기
- [x] 루틴 선택 - TableView로 구현

## 해당 task 관련 스크린샷
<img width="271" alt="스크린샷 2021-03-04 오후 4 04 15" src="https://user-images.githubusercontent.com/51286963/109924199-4622ed00-7d03-11eb-90f1-c0a7f1c5c4bb.png">

## related issue
X

## things to consider, personal feedback
X
